export const BEFORE_REQUEST_UPLOAD_FILE = 'BEFORE_REQUEST_UPLOAD_FILE';
export const SUCCESS_REQUEST_UPLOAD_FILE = 'SUCCESS_REQUEST_UPLOAD_FILE';
export const ERROR_REQUEST_UPLOAD_FILE = 'ERROR_REQUEST_UPLOAD_FILE';

export const BEFORE_REQUEST_CHECK_EMAIL_EXITS = 'BEFORE_REQUEST_CHECK_EMAIL_EXITS';
export const SUCCESS_REQUEST_CHECK_EMAIL_EXITS = 'SUCCESS_REQUEST_CHECK_EMAIL_EXITS';
export const ERROR_REQUEST_CHECK_EMAIL_EXITS = 'ERROR_REQUEST_CHECK_EMAIL_EXITS';

export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
