export const BEFORE_REQUEST_REGISTER = 'BEFORE_REQUEST_REGISTER';
export const SUCCESS_REQUEST_REGISTER = 'SUCCESS_REQUEST_REGISTER';
export const ERROR_REQUEST_REGISTER = 'ERROR_REQUEST_REGISTER';
export const FAIL_REQUEST_REGISTER = 'FAIL_REQUEST_REGISTER';

export const BEFORE_REQUEST_UPLOAD_FILE = 'BEFORE_REQUEST_UPLOAD_FILE';
export const SUCCESS_REQUEST_UPLOAD_FILE = 'SUCCESS_REQUEST_UPLOAD_FILE';
export const ERROR_REQUEST_UPLOAD_FILE = 'ERROR_REQUEST_UPLOAD_FILE';
export const FAIL_REQUEST_UPLOAD_FILE = 'FAIL_REQUEST_UPLOAD_FILE';
