export const BEFORE_REQUEST_LOGIN = 'BEFORE_REQUEST_LOGIN';
export const SUCCESS_REQUEST_LOGIN = 'SUCCESS_REQUEST_LOGIN';
export const ERROR_REQUEST_LOGIN = 'ERROR_REQUEST_LOGIN';
export const FAIL_REQUEST_LOGIN = 'FAIL_REQUEST_LOGIN';

export const BEFORE_REQUEST_LOGOUT = 'BEFORE_REQUEST_LOGOUT';
export const SUCCESS_REQUEST_LOGOUT = 'SUCCESS_REQUEST_LOGOUT';
export const ERROR_REQUEST_LOGOUT = 'ERROR_REQUEST_LOGOUT';
export const FAIL_REQUEST_LOGOUT = 'FAIL_REQUEST_LOGOUT';

export const BEFORE_REQUEST_ME = 'BEFORE_REQUEST_ME';
export const SUCCESS_REQUEST_ME = 'SUCCESS_REQUEST_ME';
export const ERROR_REQUEST_ME = 'ERROR_REQUEST_ME';
export const FAIL_REQUEST_ME = 'FAIL_REQUEST_ME';

export const TOGGLE_FULL_PERMISSION = 'TOGGLE_FULL_PERMISSION';

export const RESET_LOGOUT_REQUEST = 'RESET_LOGOUT_REQUEST';
