export const BEFORE_FETCH_LIST_ROLE = 'BEFORE_FETCH_LIST_ROLE';
export const SUCCESS_FETCH_LIST_ROLE = 'SUCCESS_FETCH_LIST_ROLE';
export const ERROR_FETCH_LIST_ROLE = 'ERROR_FETCH_LIST_ROLE';
export const FAIL_FETCH_LIST_ROLE = 'FAIL_FETCH_LIST_ROLE';

export const BEFORE_FETCH_LIST_PERMISSION = 'BEFORE_FETCH_LIST_PERMISSION';
export const SUCCESS_FETCH_LIST_PERMISSION = 'SUCCESS_FETCH_LIST_PERMISSION';
export const ERROR_FETCH_LIST_PERMISSION = 'ERROR_FETCH_LIST_PERMISSION';
export const FAIL_FETCH_LIST_PERMISSION = 'FAIL_FETCH_LIST_PERMISSION';

export const BEFORE_REQUEST_CREATE_ROLE = 'BEFORE_REQUEST_CREATE_ROLE';
export const SUCCESS_REQUEST_CREATE_ROLE = 'SUCCESS_REQUEST_CREATE_ROLE';
export const ERROR_REQUEST_CREATE_ROLE = 'ERROR_REQUEST_CREATE_ROLE';
export const FAIL_REQUEST_CREATE_ROLE = 'FAIL_REQUEST_CREATE_ROLE';

export const SUCCESS_REQUEST_REMOVE_ROLE = 'SUCCESS_REQUEST_REMOVE_ROLE';

export const PUSH_ROLE_TO_LIST = 'PUSH_ROLE_TO_LIST';

export const SUCCESS_REQUEST_UPDATE_ROLE = 'SUCCESS_REQUEST_UPDATE_ROLE';

export const BEFORE_REQUEST_UPDATE_PERMISSION = 'BEFORE_REQUEST_UPDATE_PERMISSION';
export const SUCCESS_REQUEST_UPDATE_PERMISSION = 'SUCCESS_REQUEST_UPDATE_PERMISSION';
export const ERROR_REQUEST_UPDATE_PERMISSION = 'ERROR_REQUEST_UPDATE_PERMISSION';
export const FAIL_REQUEST_UPDATE_PERMISSION = 'FAIL_REQUEST_UPDATE_PERMISSION';

export const SUCCESS_REQUEST_ROLE_INFO = 'SUCCESS_REQUEST_ROLE_INFO';
