export const SUCCESS_FETCH_WIDGET_ROUTE_LIST = 'SUCCESS_FETCH_WIDGET_ROUTE_LIST';

export const BEFORE_FETCH_WIDGET_FIELD_LIST = 'BEFORE_FETCH_WIDGET_FIELD_LIST';
export const SUCCESS_FETCH_WIDGET_FIELD_LIST = 'SUCCESS_FETCH_WIDGET_FIELD_LIST';
export const ERROR_FETCH_WIDGET_FIELD_LIST = 'ERROR_FETCH_WIDGET_FIELD_LIST';
